"""Application-wide constants — no magic numbers in business logic."""

MEETING_CODE_LENGTH = 10
MEETING_CODE_MIN = 1_000_000_000
MEETING_CODE_MAX = 9_999_999_999
MEETING_CODE_MAX_RETRIES = 5

DURATION_MIN_MINUTES = 5
DURATION_MAX_MINUTES = 1440

OTP_LENGTH = 6
OTP_TTL_SECONDS = 300
OTP_COOLDOWN_SECONDS = 60
OTP_MAX_ATTEMPTS = 3
OTP_LOCK_SECONDS = 1800
OTP_MAX_REQUESTS_PER_HOUR = 3
OTP_SPAM_LOCK_SECONDS = 3600

LOGIN_MAX_FAILURES = 5
LOGIN_LOCK_SECONDS = 900

WS_TICKET_TTL_SECONDS = 30
WS_MAX_MESSAGE_SIZE = 16 * 1024  # 16 KB
WS_HEARTBEAT_INTERVAL = 25
WS_STALE_THRESHOLD = 60

PRESENCE_CACHE_KEY_PREFIX = "room:"
RATELIMIT_KEY_PREFIX = "rl:"

IDEMPOTENCY_TTL_SECONDS = 86400  # 24h
DISTRIBUTED_LOCK_TTL_MS = 5000

MEETING_CACHE_TTL = 60  # seconds

DISPLAY_NAME_MAX_LENGTH = 60
CHAT_MESSAGE_MAX_LENGTH = 2000
